### PR TITLE
change datetime parsing method

### PR DESCRIPTION
**Pull request by changukshin**
related issue : #19

replaced datetime parsing method to standard module named `dateutil.parser`.

tested(succeeded)
- Hyphens
    - '30-Nov-2022'
    - 'Nov-30-2022'
    - '30-8-22'
    - '30-Nov-22'
    - '30-November-22'
- No space
    - '30Nov2022'
- Space
    - '30 November 2022'
    - 'Nov 30 2022'
    - '30 Nov 2022'
    - '30 08 22'
    - '30 8 22'
- Slash
    - '30/08/22'
    - '30/Nov/22'
    - '30/November/22'
- Mixed
    - '30November 2022'
    - '30Nov       22'
    - 30/November 22'

### CODE REVIEW

**Review by siewyeng — CHANGES_REQUESTED** [review]
I don't think dateutil parser can parse the string "today"

**Comment by ThorpeJosh** [comment]
What happens with 10th November?
Does it follow Int or American date scheme? Or throw error?

**Comment by changukshin** [comment]
[10th November]

1. "10th November" -> 10-November-2022
2. "10th Feb" -> 10-Feb-2022

- Confirmed that when user omitted the year, this library uses current year to fill.
- Confirmed it can parse "st"/"nd"/"rd"/"th"

---

[Consistency - presented by @ThorpeJosh and @siewyeng ]

**When someone insert "3/4/2022" it could be parsed as "4th March" or "3rd April".**
with default (dateutil) configuration, "3/4/2022" goes to "4th March".

default logic of dateutil:
- First, if query is matched into "month/day/year", treat as "month/day/year"
- When the first clause failed, backed-off to "day/month/year"

The point of the issue here is standard formatting i think.
**Here I am proposing we follow international standard, "yyyy-mm-dd"**
refer : https://en.wikipedia.org/wiki/ISO_8601

**if the user input does not match international standard, we can ask user to confirm the correct date.**
**(let our user can insert all combination of above)**

(help message need to be updated if we confirm this)

Asking for advice/revising/confirmation.
@ThorpeJosh  @siewyeng  @lamchuntat

**Comment by changukshin** [comment]
Conclusion

We all agreed the default format.
We only accept DMY and YMD. 
**(Inserting MDY or YDM is undefined behavior)**

For ambiguity between DMY and YMD, follow this logic:
- When user use 4 digit Y, it could always be parsed correctly.
- When user use 2 digit Y, always select the nearest(and upcoming) date.

    - ex 1) : Most general way to express date using 2 digit Y.
        - TODAY : 2022-10-23
        - QUERY : "24-10-22" | "24/10/22" | "24 10 22"
        - PARSED : 2022 Oct 24th
 
    - ex 2) : USER inputs YMD but 2 digit Y. This case is rare.
        - TODAY : 2022-10-23
        - QUERY : "22-10-24" | "22/10/24" | "22 10 24"
        - PARSED : 2022 Oct 24th

It is quite safe because we always submit timesheet for 'upcoming' dates(including 'today').
The other query user inserted would be denied and quit the program with the instruction.

**Comment by changukshin** [comment]
Final conclusion.

4 digit years : we can always guarantee it will be accepted.
2 digit years : select nearest candidate between (YMD/DMY).

**Comment by changukshin** [comment]
Supported date formats.
Example date : 17th Feb 2009

- DMY
    - DD/MM/YY : 17/02/2009
    - D/M/YY : 2/17/2009
    - DD-MM-YY : 17-02-2009
    - D-M-Y : 17-2-2009
    - DD MM YY : "17 2 2009"
    - D M Y : "17 2 09"

- YMD
    - YY/MM/DD : 2009/02/17
    - YY/M/D : 2009/2/17
    - YY-MM-DD : 2009-02-17
    - Y-M-D : 09-2-17
    - YY MM DD : "2009 02 17"
    - Y M D : "09 2 17"

Unsupported
- YDM
- MDY
- other separators. (for example : underscore)

Comment
- If user want to use space as a separator, he have to wrap them with quotes.

**Comment by changukshin** [comment]
All settled. Need review

@ThorpeJosh @siewyeng @lamchuntat

**Review by siewyeng — APPROVED** [review]

**Pull request merged**
