### PR TITLE
perf: skip docker instantiation if selected dates fall on weekends only

### PR DESCRIPTION
**Pull request by lamchuntat**
Rename "date_fn".

Check whether selected dates only include weekends, don't launch Docker if that is the case.

### CODE REVIEW

**Review by ThorpeJosh — COMMENTED** [review]
Looks good.

How do you feel about adding a unit test for the `get_working_dates` func?
This would cover the 3rd test case in #21

**Comment by lamchuntat** [comment]
Yup sure! Let me tackle it 👌

**Comment by lamchuntat** [comment]
@ThorpeJosh @siewyeng @changukshin I think this is ready for review!

**Review by ThorpeJosh — APPROVED** [review]
Awesome. Nice test cases

**Pull request merged**
